export const WRITING_PROMPTS = [
  "What surprised you today?",
  "Who made you smile or laugh?",
  "What did you notice that you usually walk past?",
  "What conversation will you remember from today?",
  "What felt hard today — and how did you get through it?",
  "Was there a moment of silence or stillness today?",
  "What small thing went better than expected?",
  "Who were you thinking about and why?",
  "What did someone say that stuck with you?",
  "What are you grateful for that you almost didn't notice?",
  "Was there a moment you almost didn't experience?",
  "What made today different from yesterday?",
  "Who helped you today, even in a small way?",
  "What did you see, hear, or smell that transported you somewhere?",
  "When did you feel most like yourself today?",
  "What did you do today that you'd want to remember in 10 years?",
  "When did you feel proud of yourself?",
  "What made you curious today?",
  "What are you looking forward to?",
  "What would you do differently today if you could?",
  "What did your body feel like at some point today?",
  "What was the hardest choice you made today?",
  "Who or what gave you energy today?",
  "What moment today was so small, you almost missed it?",
];
